### ISSUE TITLE
Crosshair/Placement thing (?) visible through blocks.

### ISSUE THREAD

**Issue by wafflethings** [Caeden117/ChroMapper#120]

**Comment by AsoVR** [comment]
Can we have an image of the issue?

**Comment by the-garbage-which-belongs-to-waffle** [comment]
![Image](https://user-images.githubusercontent.com/60797216/86124330-e1a7f200-bad2-11ea-9308-7332c95bd060.png)
Although visibly behind the crosshair, it is actually half-way through when seen from the side.
![Image2](https://user-images.githubusercontent.com/60797216/86124416-0308de00-bad3-11ea-928b-4d7b1629c1c6.png)

**Comment by Caeden117** [comment]
Closing due to age, this has been fixed a long time ago
