### ISSUE TITLE
Funny editor scale doesn't scale with bpm unlike mediocre mapper

### ISSUE THREAD

**Issue by ZeFoxyBoi** [Caeden117/ChroMapper#141]
![image](https://user-images.githubusercontent.com/69172089/89230015-68029880-d597-11ea-8a18-da41fd8783d7.png)
Image of 500 editor scale at 479.5 bpm in MM

![image](https://user-images.githubusercontent.com/69172089/89230316-e7906780-d597-11ea-8c09-9d1fe31151c3.png)
Image of same song at 20 editor scale in CM

You can't really tell, and I don't wanna record a video atm (if you want I could) but the song just fucking zooms by in CM while in MM it goes slow boy

For another song
![image](https://user-images.githubusercontent.com/69172089/89230446-2a523f80-d598-11ea-82c5-8cefdcd22311.png)
Same editor scale just at 242 bpm, it scrolls by at the same speed and is the same distance apart (MM)

![image](https://user-images.githubusercontent.com/69172089/89230598-7309f880-d598-11ea-8f9d-a3cf3e37a3f2.png)
Same editor scale just at 242 bpm, this time it scrolls by much slower than the 479.5 bpm song in CM but in MM it scrolls by at the same speed.

**Comment by Caeden117** [comment]
Hmm, I do not see any buggy behavior that needs to be fixed, but rather behavior is not the same in MediocreMapper. So unfortunately, this is not something I intend to change.

While on the topic, I would just like to clarify: ChroMapper is not intended to be a 1:1 clone of MediocreMapper. Decisions have been, and will be made, that are different from the choices made in MediocreMapper.

Sorry if that felt a bit rude, I took this whole issue as "this is not like mediocremapper please fix".
