### ISSUE TITLE
Box Select leaves extra blocks

### ISSUE THREAD

**Issue by xypherorion** [Caeden117/ChroMapper#151]
Updated to latest yesterday after the undo fixes. 
When using the box select it consistently leaves an extra block wherever you click to start it, and it appears after you finish the select. Seems like maybe a "box select is enabled" type check had been missed, and not disabled block placement.
Thanks again!

**Comment by Caeden117** [comment]
Closing due to age, this should have been fixed a long time ago (Feel free to re-open if issue persists)
