### ISSUE TITLE
Start Beat Offset doesn't recalculate properly when Negative

### ISSUE THREAD

**Issue by xypherorion** [Caeden117/ChroMapper#158]
You also have to hit "save difficulty" before it recalculates the new value, too.

![image](https://user-images.githubusercontent.com/2755605/91191569-f2d04200-e6c2-11ea-882d-91bee3e19bb3.png)
![image](https://user-images.githubusercontent.com/2755605/91191604-fd8ad700-e6c2-11ea-8363-948c3a26c7ab.png)
![image](https://user-images.githubusercontent.com/2755605/91191652-08de0280-e6c3-11ea-987f-df3b49e6f3a2.png)

**Comment by Top-Cat** [comment]
That UI doesn't even exist anymore...

![image](https://user-images.githubusercontent.com/534069/91191918-4192d180-e6ed-11ea-989d-c3159d6d8b72.png)

**Comment by xypherorion** [comment]
![image](https://user-images.githubusercontent.com/2755605/91192738-48591e80-e6c4-11ea-8588-e49787f1bfa3.png)
Uhhh...so whats the point of the github being public if you're not going to update it, then?
Plz fix. I'm happy to be a patron but i prefer to compile it myself so i'm not getting all the extra Unity services crap.

**Comment by XAce1337manX** [comment]
dev branch
![image](https://user-images.githubusercontent.com/68104413/91192933-e0451f80-e739-11ea-9142-7877e546b81b.png)

**Comment by Caeden117** [comment]
Closing due to age, feel free to re-open if issue persists
