### ISSUE TITLE
BTS Environment: Back Lasers are not mapped to anything

### ISSUE THREAD

**Issue by marcoboy123** [Caeden117/ChroMapper#179]
Center Lights (As shown in the picture) are affecting the BTS Logo Light right now inside Chromapper, although it shouldnt.
Back Lasers should be mapped to that light, Back Lasers do not show any change in Chromapper though.
![](https://puu.sh/GOaVp/b03e3c0cc6.png)

**Comment by Caeden117** [comment]
Already addressed by #178
