### ISSUE TITLE
I wonder if you will make a public/open beta for others to use. If you feel people will complain, it's a beta. Betas have problems. It's ok.

### ISSUE THREAD

**Issue by QuantumWormhole** [Caeden117/ChroMapper#235]

**Comment by PaperT1D** [comment]
Chromapper is in constant development. Why not support the people creating it? Not to mention, nothing is really stopping you from building Chromapper yourself, you just won't get any support. Check out the readme, it pretty much explains what you need to know.

**Comment by Caeden117** [comment]
ChroMapper is currently going through a large internal rewrite (see [zenjectification](https://github.com/Caeden117/ChroMapper/tree/zenjectification)), and after that (with a few other additions), I'll consider a public beta
