### ISSUE TITLE
Plugins not loading.

### ISSUE THREAD

**Issue by QuantumWormhole** [Caeden117/ChroMapper#239]
Yes, I tried every plugins folder. Beat saber data, Beat saber, and ChroMapper

**Comment by Caeden117** [comment]
Need more info. What plugin are you trying to install?

**Comment by QuantumWormhole** [comment]
Mapping Extensions.

**Comment by Caeden117** [comment]
This appears to be an issue for Beat Saber modding, not ChroMapper.

In that case, [please read the Beginner's Guide on the BSMG Wiki](https://bsmg.wiki/beginners-guide.html). If you are on PC, you can use ModAssistant to download Mapping and Noodle Extensions (while also downloading all the dependencies that they need to run). If you are on Quest, then unfortunately you are out of luck when it comes to Noodle Extensions; there is currently no version of NE for Quest.
