### ISSUE TITLE
{Suggestion}[New Beatsaber environment] Can you Add The new environment On to Chromapper!

### ISSUE THREAD

**Issue by starvide** [Caeden117/ChroMapper#280]
This is most likely To Get removed soon But Can you add the New environment on Chromapper so i can Mess with it
Even though i can look at it in game!

**Comment by Caeden117** [comment]
The update literally came out today. ChroMapper contributors do have lives outside of the project, and those have priority. We'll get to the Interscope environment sometime in the near future, please be patient.

**Comment by Jd-Gamer65** [comment]
JESUS EFFING CHRIST THE UPDATE CAME OUT ON THE EXACT DATE YOU MADE THIS!!!!! The devs of chromapper have lives! So at least be PATIENT and WAIT like a NORMAL PERSON! smh.

**Comment by starvide** [comment]
9days left

**Comment by starvide** [comment]
I might just close this for Right now

**Comment by starvide** [comment]
1000years left

**Comment by starvide** [comment]
"about 100 Years has Pasted now  And it should Take them About another year "
