### ISSUE TITLE
Audio seeking error thrown

### ISSUE THREAD

**Issue by rfcaps** [Caeden117/ChroMapper#288]
When loading the song, the seeking position is not correct and an error is thrown. The note seems to be behind the grid and the waveform is also off. Attached is my log file.
[Log.txt](https://github.com/Caeden117/ChroMapper/files/6586748/Log.txt)

**Comment by Caeden117** [comment]
Closing due to age. This is a Unity issue caused when you attempt to play a song outside of the song bounds
