### ISSUE TITLE
ChroMapper crashing upon startup (ARM64)

### ISSUE THREAD

**Issue by mixedissmiling** [Caeden117/ChroMapper#346]
**ChroMapper version**
What version of ChroMapper are you running? It can be seen by pressing `Escape` in the Editor, or on the bottom right of the Options menu. If you clone and built ChroMapper from the source, what commit did you clone from?

Latest (Official) Release

**Describe the Issue**
Type a clear and concise description of what the problem is.

ChroMapper literally won't let me use it

**Provide Screenshots or Videos**
Providing screenshots and videos (especially if you are encountering an error message) will help a lot to helping us debug the issue.

If the Development Console is open and showing errors, ***PLEASE*** click on the specific error to open the Stack Trace. The "Stack Trace" is the exact location in ChroMapper's code that caused the error, and how it was executed. Providing the Stack Trace with your bug report will allow us to immediately find and fix the problem.

**Steps to Reproduce**
Describe the exact steps which reproduce the problem in as many details as possible.

Open

**Expected Behavior**
What did you expect to happen? How did this differ from what actually happened?

I expected it to open as normal.

**Additional Context**

none

**Comment by Top-Cat** [comment]
1. Latest is not a version, the template tells you clearly how to find your version
2. You didn't provide any screenshots, videos or console output as also described in the template.

Please actually complete the template.

**Comment by Caeden117** [comment]
Template aside, ARM64 is not a platform we anticipated nor have official builds for. We should've specified that the official builds are only for x64.

**Comment by AwesomeCE110** [comment]
I apolgize for the issue with the template. And, I don't see how x64 emulation didn't kick in. Either way, to complete the template to the best of my abilities, the version is 0.8.0, thank you for your time, be blessed.

**Comment by AwesomeCE110** [comment]
I'll definitely try this! it all just depends on id it will work in command
prompt on windows
