### ISSUE TITLE
Linux release

### ISSUE THREAD

**Issue by Lindenk** [Caeden117/ChroMapper#347]
**What is your request?**
A prebuilt linux build of ChroMapper

**What problem does this solve?**
Currently anyone using linux needs to install unity, activate a license, and pray nothing breaks in the process. Running through wine doesn't work because the launcher relies on internet explorer for it's updates on windows. Cross building for linux shouldn't be much harder than selecting it as a build target.

**Comment by Caeden117** [comment]
Hi,

While the ChroMapper *Launcher* does not currently support Linux (there are currently problems with getting UI to work), [we do have prebuilt Linux builds available from Jenkins](https://jenkins.kirkstall.top-cat.me/view/All/job/ChroMapper/).

I've updated the latest GitHub Release to address that confusion. Sorry about that.

Feel free to re-open the issue if you have any questions.

**Comment by Lindenk** [comment]
Ah that works, thank you. I might also repackage it for the aur if that's alright

**Comment by Top-Cat** [comment]
I think it would be better to keep everything going through the launcher. One of the bigger problems MMA2 had is people being on ancient versions complaining about or using features that had been changed or fixed months ago.

There's already a working version of the launcher for linux that we're currently testing and it should be available soon.

Of course you're welcome to build the application yourself but I'd ask that you don't redistribute our binaries.
