### ISSUE TITLE
Confirm On Delete

### ISSUE THREAD

**Issue by MasterAirscrachDev** [Caeden117/ChroMapper#350]
**What is your request?**
Either Add A Confirm On Delete (In The Song Info Menu) Or Move The Delete So It's Not Right Next To The Save Button.
**What problem does this solve?**
So People Don't Accidentally Delete Their Maps.

**Additional context**
I Had Just Saved My Diff Name And Went To Save Song Infos, Clicked To Early. *Poof* Map Gone (Fortunately It Was A Test Map)
![image](https://user-images.githubusercontent.com/45087290/136895068-a402ca38-9a13-46c5-921b-074f32a2c9bc.png)

**Comment by Caeden117** [comment]
This confirmation box has been here for a long time.

![image](https://user-images.githubusercontent.com/30004286/136895473-a2990487-d5a5-4bcc-a321-076b0b3d4272.png)
