### ISSUE TITLE
Refuses to launch on ChromeOS via Crostini

### ISSUE THREAD

**Issue by CorruptedPlazma** [Caeden117/ChroMapper#369]
**ChroMapper version** 
0.8.454

**Describe the Issue**
Linux executable doesn't open in Crostini, ChromeOS's built in Linux VM. Fails with `exec format error`, implying mismatched architectures, but my Chromebook is an x86_64 machine.

**Steps to Reproduce**
Create a Crostini container on ChromeOS, download Linux executable and move it to Linux, run `chmod +x` on the executable, attempt to execute. Bash will return a "command not found" Copy the executable to `/bin` and attempt to execute again, returning `-bash: /usr/bin/CML-Linux: cannot execute binary file: Exec format error`

**Expected Behavior**
Since my machine has an x86_64 processor, I would think the app would open fine. 

**Additional Context**
Using ChromeOS 98 beta, Crostini is using Debian 11 (bullseye).

**Comment by Top-Cat** [comment]
Have you installed mono?

**Comment by GalaxyMaster2** [comment]
Don't run it from /usr/bin, it won't have proper permissions. It's intended to be run in a user-owned directory. From what I can see you probably just tried to execute it as if it were a global command, not a local executable. `./CML-Linux` is what you would want to do if you were in the directory where it's located.

In addition, install mono if you haven't already as TC mentioned.

**Comment by CorruptedPlazma** [comment]
I see. I'm working on installing mono and I'll run it in my home directory again, I'll close this issue and look to other resources if needed.
