### ISSUE TITLE
Fetching Object ID Through Chromapper

### ISSUE THREAD

**Issue by LostALife** [Caeden117/ChroMapper#372]
**What is your request?**
Being able to hover over an object to get its object id in the environment and access it's Chroma custom data through the node editor. Allowing the user to move the object in the environment as you would with Chroma through the .dat files.

**What problem does this solve?**
This would remove the need to use the logs to get an objects id. 
It would also mean you could do all the work through chromapper instead of having to go through the .dat files to edit the environments.

**Comment by TzurS11** [comment]
Just script the environment

**Comment by Top-Cat** [comment]
Chromapper does not and legally never will have accurate environments, we can't show ids we don't have

**Comment by TzurS11** [comment]
To add to what i said most mappers that use chroma and noodle extensions probably script for having much more control and making things that are almost impossible and time consuming
Editing the dat file is not ideal.
If you don't know how to script then you can take scuffed walls which is a tool that can help you(it's a text based and not code based)

**Comment by LostALife** [comment]
Yeah thats fair enought. I do use SW and that's good.
