### ISSUE TITLE
My plugins won't load.

### ISSUE THREAD

**Issue by XJSWAG** [Caeden117/ChroMapper#380]
I'm pretty sure I'm running the latest version

I'm putting plugins in to the plugins folder but when I go in ChroMapper they don't show up.

I don't get any errors

**Comment by Caeden117** [comment]
Check the [FAQ page and see if that solves your problem](https://chromapper.atlassian.net/wiki/spaces/UG/pages/806682666/Frequently+Asked+Questions+FAQ#I%E2%80%99ve-installed-some-Plugins-correctly,-but-ChroMapper-doesn%E2%80%99t-load-them.-What-gives?).

**Comment by XJSWAG** [comment]
Ok

**Comment by XJSWAG** [comment]
Oh I found the solution. You can close this issue now.
