### ISSUE TITLE
Beatmap v3 Feedback Megathread

### ISSUE THREAD

**Issue by Caeden117** [Caeden117/ChroMapper#386]
**BEATMAP V3 DOES NOT HAVE A PUBLIC BETA. IF YOU DONT KNOW COMPILE CHROMAPPER FROM SOURCE, PLEASE DO NOT ASK HOW TO ACCESS IT EARLY.**

If you are using Beatmap v3 early, please report all issues and feedback here.

**Comment by GalaxyMaster2** [comment]
Reposting earlier feedback that still applies, and some new things

Arcs:

- [ ] If one of the notes is a dot note, making an arc does not work. If you manually edit the cut direction to 8, it is treated as down. In game the effect seems to be the same as setting the multiplier to 0.

- [ ] Mid anchor mode is ignored. See the bsmg wiki for the situations in which it applies: https://bsmg.wiki/mapping/map-format.html#m-2

- [ ] Performance still seems to be quite bad. With only a couple arcs present I'm getting slight hiccups when starting playback, which also seems to desynchronize hitsounds for a bit.

Chains:

- [ ] The head note is positioned in the middle of a grid cell, while in game it is positioned as if it were a full note, with part of it chopped off.

- [ ] Slice count on alt+scroll is limited to 3, but in game it works perfectly down to 2 (and even 1, though that is probably outside of intended use).

- [ ] The curve calculation for chains is not correct, which is mostly noticeable on larger rotations.

- [ ] Slices seem to have some unintended rotation on other axes, which increases the more spaced out in time it is from the head note.

- [ ] Squish amount also affects the location in time of the slices, which does not happen in game.

- [ ] In some situations the head note model isn't properly updated. I haven't quite figured out exactly when this happens.

- [ ] Chains only have a hitsound for the head note. Currently this is accurate to how it is in game, however this is supposedly still being worked on, so something to keep an eye on.

Overall:

- [ ] Angle offset is not supported on notes, and is reset to 0 when a map using them is loaded.

- [ ] Walls now have more options for height and y position, and can use any x position. I would like to see placement options extended to reflect these new possibilities.

- [ ] Walls outside the 4 lanes currently automatically adds a Mapping Extensions requirement, but this is not necessary anymore.

- [ ] Arcs and chains spawn much further away than notes during playback.

- [ ] Chains don't respect the Simple Blocks option. They retain the shiny look.

- [ ] I would like to see alt+drag controls for both arcs and chains.

- [ ] We might also want to consider more direct ways of placing arcs and chains as an alternative placement option.

- [ ] I would like at least support for converting 2.6.0 maps with arcs to 3.0.0, even if saving in that format won't be added. I had to manually convert arcs on one of my maps.

**Comment by CCDV2** [comment]
Metioned by others and I also exprienced.
> Having an issue where the application starts lagging gradually over time.

**Comment by brochasep** [comment]
How do I... access beatmapV3 in chromapper?

**Comment by CCDV2** [comment]
> How do I... access beatmapV3 in chromapper?

You can refer to `V3CONTROL.md` in that branch.

**Comment by brochasep** [comment]
> > How do I... access beatmapV3 in chromapper?
> 
> You can refer to `V3CONTROL.md` in that branch.

where do I find it?

**Comment by brochasep** [comment]
> > > How do I... access beatmapV3 in chromapper?
> > 
> > 
> > You can refer to `V3CONTROL.md` in that branch.
> 
> where do I find it?

never mind, found it

**Comment by CoopPlayzz** [comment]
how can you do it on a Mac?

**Comment by CoopPlayzz** [comment]
and can u get it by having your version on dev. or stable in chromapper settings?

**Comment by xmadb4x** [comment]
how do i download the beatmap v3 beta?

**Comment by Caeden117** [comment]
To be quite frank: in its current state, if you don't know how to compile ChroMapper from source, you are honestly better off not using the beatmap v3 beta.

It's *functional* but that's it.

**Comment by xmadb4x** [comment]
> To be quite frank: in its current state, if you don't know how to compile ChroMapper from source, you are honestly better off not using the beatmap v3 beta.
> 
> It's _functional_ but that's it.

ok

**Comment by JD-The-65th** [comment]
Adding on from another thread, chains and arcs don't respect the visibility set for preview (play) mode and always default to the user defined visibility. I'm currently working to see if I can fix this, but don't count on me.

**Comment by CCDV2** [comment]
Chain could set `sc` to 1. In such case, only a head note with direction will be shown.

**Comment by JD-The-65th** [comment]
There needs to be a way for arcs to render over the measure grid without affecting the user's transparency setting, it'd help when you make a pattern and delete an block that goes along with the arc, but the arc still stays there.

**Comment by bc3tech** [comment]
Are we tracking work items that need to be completed somewhere so we can attach commits & PRs to them as we knock 'em out?

**Comment by JD-The-65th** [comment]
No, not really. Although that does give me an idea. GitHub Projects would be nice to look into.

**Comment by bc3tech** [comment]
yup - is a great way to organize & track work if you know what you need to get done :)

**Comment by JD-The-65th** [comment]
Rotation Events get deleted when using the new Official Editor in conjunction with the V3 Branch

**Comment by Meivyn** [comment]
No clue if that thread is still being watched, but I noticed this while playing Joetastic maps:

![image](https://user-images.githubusercontent.com/793322/190836920-d1f47026-4818-430e-9e07-2ea22f19d878.png)

You can see that I didn't miss and that the arc isn't connected to the saber. This seems to happen when an arc is tied to a chain.

**Comment by XAce1337manX** [comment]
Not a bug. The arc is not connected to the block so it can't magnetise. (It's connected to the chain tail end which isn't a block.)
![image](https://user-images.githubusercontent.com/68104413/190838441-d926cfa1-5824-46c0-8d83-73b71066768c.png)

**Comment by Meivyn** [comment]
Well this looks like a bug to me. But rather a base game bug than a ChroMapper one. But thanks for pointing it out.

**Comment by Numptynizz** [comment]
Have mapped a full map on v3 - chromapper is working great on my (old but fairly high spec) computer. Since I've mapped it in V3, and I have a quest 2, I have absolutely no way of properly mapping lighting since it's not updated; it's unfortuante, but I'll just have to wait to upload my map - I accidently mapped lighting for the whole song without realising it doesnt work properly lol. Some of the lighting does work, but it seems to be pretty random which lighting events work and when (seems like the 'off' lighting is the most inconsistent?).

A few questions:
If I create a second map, is it wise to complete it in v2 chromapper, do the lighting, then convert it to v3 and add arcs and chains? Will the lighting carry over properly?
Is there any sort of timeframe of how long it'll be until I can update the lights on my original map (even it's super broad or "it's not being worked on yet")?
Finally, does anyone know of any way to map my v3 map lighting properly without using the official PC BS mapper?

Thank you I love this program, it's incredibly easy to use and it makes mapping very fun! <3

**Comment by XAce1337manX** [comment]
v3 lighting is implemented for Weave and TheSecond environment (with PR pending for Weekend). If you do not have those environments, your build is not up to date. 

Check your Environment Effects on game to set to All Effects. On non-Ex+, it is set to No Flickering which will drastically affect lights. Chroma is not supported on v3 map format yet despite what CM does. 

No estimate on v3 being featuring complete and ready. 

Further questions are easier to answer in the Discord.

**Comment by The-Techy** [comment]
> v3 lighting is implemented for Weave and TheSecond environment (with PR pending for Weekend). If you do not have those environments, your build is not up to date.
> 
So I know this is an old issue, and maybe I'm just being stupid, but I just cannot figure out how to get V3 lighting in Chromapper (or anywhere other than the official editor, and I don't have a powerful enough PC). Am I missing something? None of the V3 environments come up as options in Chromapper, and I basically can't find anything about it online. Thanks!

**Comment by XAce1337manX** [comment]
V3 lighting is not implemented in the current release of CM.
(Was removed in order to refactor the beatmap model.)

**Comment by The-Techy** [comment]
Ah ok. Any idea if might be implemented in the future? And if so, any kind of timeline? Thanks
