### ISSUE TITLE
beatmap v3 quest support

### ISSUE THREAD

**Issue by 1naynay** [Caeden117/ChroMapper#401]
was looking for solutions to play maps i made with arcs and chains on my quest. beat saber does not support crossbuy on pc and was looking for a way to playtest my own maps.

easy solutions preferred: i do NOT want to spend $30 for arcs haha

**Comment by Top-Cat** [comment]
Not sure why you're asking a map editor to add features to beat saber?

**Comment by Caeden117** [comment]
Use the [testplay guide on the Wiki](https://bsmg.wiki/mapping/#testing-on-a-quest) to play WIP maps on Quest.
