### ISSUE TITLE
Jenkins CI for Beatmap-v3

### ISSUE THREAD

**Issue by Anti-Apple4life** [Caeden117/ChroMapper#403]
**What is your request?**
I would like to have Jenkins set up to build the beatmap-v3 branch automatically.

**What problem does this solve?**
This should be implemented because a lot of people might not have the resources to build ChroMapper themselves, and want to make v3 maps. This will solve that problem.

**Additional context**
I ran into errors with Unity on Linux, and could not find mono for unity on linux.

**Comment by Anti-Apple4life** [comment]
My problem is that I cannot find mono for linux in Unity Hub

**Comment by JD-The-65th** [comment]
You don't. Plain as that. I compiled it without anything special and it works properly

**Comment by Anti-Apple4life** [comment]
> You don't. Plain as that. I compiled it without anything special and it works properly

with IL2CPP?

**Comment by JD-The-65th** [comment]
With whatever unity came with. Nothing special
