### ISSUE TITLE
Default hotkeys are reversed ( default up direction note hotkey is "s" instead of "w" )

### ISSUE THREAD

**Issue by slender9168** [Caeden117/ChroMapper#406]
**ChroMapper version**
V0.8.454

**Describe the Issue**
the default hotkeys to change notes directions are reversed & are not intuitive. ( default hot key for up note direction is "s" instead of "w" )

**Steps to Reproduce**
install a fresh copy of ChroMapper on a new pc.

Thanks :)

**Comment by TzurS11** [comment]
This is not mma2

**Comment by slender9168** [comment]
> This is not mma2

ok, I found them not intuitive and thought that was a glitch, thanks for the help
