### ISSUE TITLE
Billie Environment Breaks My Maps & Lighting

### ISSUE THREAD

**Issue by Kaylerr** [Caeden117/ChroMapper#411]
**ChroMapper version**
0.8.454

**Describe the Issue**
When mapping with the Billie Environment, adding lights to the map breaks it when triggering the Sun or the Water tracks, this results in only singular notes being instantiated in Beat Saber per second or so, so the map is instantiating notes too late. The environment also stops animating and lighting itself.

**Provide Screenshots or Videos**
There are literally no screenshots.

If the Development Console is open and showing errors, ***PLEASE*** click on the specific error to open the Stack Trace. The "Stack Trace" is the exact location in ChroMapper's code that caused the error, and how it was executed. Providing the Stack Trace with your bug report will allow us to immediately find and fix the problem.

**Steps to Reproduce**
Add a sun lighting event and add a few notes after it and you will see.

**Expected Behavior**
I expected the map to work as usual and the sun to animate correctly. 
Instead, the map, after the sun event has been parsed, just instantiates one note a second or so after, like above.

**Additional Context**
None.

**Comment by JD-The-65th** [comment]
What version of beat saber are you using? Also, can we have a link to the map in reference?

**Comment by Kaylerr** [comment]
I'm using Beat Saber 1.21.0, and you can view the map in-game, by getting this: [Epiphany Broken.zip](https://drive.google.com/file/d/1WQCjb4Ge0KukSHAw6_3Uau7_UV1A9oUB/view?usp=drivesdk)

**Comment by Kaylerr** [comment]
My bad. I screwed up. This should be the right [recovered broken epiphany.zip](https://github.com/Caeden117/ChroMapper/files/8929589/recovered.broken.epiphany.zip)

**Comment by XAce1337manX** [comment]
This map zip contains no events.
Adding lights also functions normal. (BS Version 1.23.0)

**Comment by Kaylerr** [comment]
wrong autosave. Damn it.
I'll definitely find it and bring it back by the end of today

**Comment by PixelHUN** [comment]
This definitely seems like an issue. I'm currently facing the same problems and removing my lighting fixes the map itself. :/

**Comment by XAce1337manX** [comment]
This issue is fixed in dev CM.
