### ISSUE TITLE
High GPU Utilisation in Windows 11

### ISSUE THREAD

**Issue by Perseus392** [Caeden117/ChroMapper#414]
**ChroMapper version**
v0.8.454

**Describe the Issue**
High Gpu Utilisation in Windows 11 which is causing thermal issues and high fan speed in Laptops and PC. 
GPU Utlisation is 95%+ on Default graphics preset.
GPU Utilisation is 40% when Graphics settings are set to the lowest Graphics Preset.

**Steps to Reproduce**
- Open Chromapper Editor on Windows 11
- Use the default graphics settings
- After a few minutes your gpu fans should be operating at Max Speed and Utilisation will be at 95% + 

**Expected Behavior**
Gpu utilisation really shouldn't be that high especially on Mid-High tier Hardware. 

**Additional Context**
Specs:
Computer Name : Lenovo Legion 5 Pro 2021
CPU: Ryzen 7 5800h
GPU : Geforce RTX 3060 
RAM : 16GB 

![Chromapper High GPU](https://user-images.githubusercontent.com/50683885/180198029-6156cd04-c9b8-4149-85ab-22f8d573dbbd.jpeg)

**Comment by Top-Cat** [comment]
Try reducing your fps or enabling vsync?
![image](https://user-images.githubusercontent.com/534069/180200850-7b4a74b8-6da6-4219-84c8-deb9be5a63d9.png)

**Comment by Perseus392** [comment]
> Try reducing your fps or enabling vsync? ![image](https://user-images.githubusercontent.com/534069/180200850-7b4a74b8-6da6-4219-84c8-deb9be5a63d9.png)

Yup, Vsync was already enabled. i now set the framerate to 60 and tried again. doesn't seem to help
![Chromapper with Vsync on and Sixty FPS](https://user-images.githubusercontent.com/50683885/180204268-0cb3d3c3-1421-4488-9cab-b959ed7bbf1b.jpeg)

**Comment by Top-Cat** [comment]
Not running Win11 so maybe worth getting someone who is to try but even with reflections on I'm barely using my older GPU
![image](https://user-images.githubusercontent.com/534069/180213019-df617e88-37a7-491e-a046-7062a48a7aab.png)

**Comment by Perseus392** [comment]
> Not running Win11 so maybe worth getting someone who is to try but even with reflections on I'm barely using my older GPU ![image](https://user-images.githubusercontent.com/534069/180213019-df617e88-37a7-491e-a046-7062a48a7aab.png)

a friend of mine with win 11 also has the same issue - high gpu utilisation. but works fine on his Win10 system.

**Comment by murl-digital** [comment]
I'm on Windows 11 with an R7 3700x and RTX 3080, I'm not seeing 95+ usage, more about 45.

**Comment by TzurS11** [comment]
im on win 11 i have i7-8700 and rtx 3060 and my GPU usage is not even going above 10(somewhere between 2 and 8)...
try lowering your graphic settings.
there are a lot of useless settings you don't need.
![image](https://user-images.githubusercontent.com/90769470/182585095-afdaac40-c91a-4c72-b159-0e39989fcb50.png)

**Comment by TzurS11** [comment]
My settings:
![image](https://user-images.githubusercontent.com/90769470/182585256-e12bc25c-366c-401a-a135-c3d837685f39.png)
![image](https://user-images.githubusercontent.com/90769470/182585292-358752da-7bad-42ac-905f-a4a2e3b9b184.png)

**Comment by Silver-Volt4** [comment]
Turning off Environment reflections drops GPU usage from 95% to 8%.

**Comment by XAce1337manX** [comment]
This is probably caused by Environment Reflections.
