### ISSUE TITLE
Shifting Movement Keybind is Vector2 instead of Vector4

### ISSUE THREAD

**Issue by Yasu3D** [Caeden117/ChroMapper#419]
**ChroMapper version**
v0.8.454

**Describe the Issue**
Editing the _Shifting Movement_ keybind (standard is 4 inputs) will only allow 2 inputs to be recognized. If you try to then select a note and move it, it'll give you an error and the note won't move. (see Paste.ee link).

**Steps to Reproduce**
Edit the keybind, select a note and try to move it.

**Expected Behavior**
4 available keybinds for _Shifting Movement_

**Additional Context**
https://paste.ee/p/Deuqa

https://user-images.githubusercontent.com/64372170/191922178-52ed0482-1f0e-4887-9667-a654f3b62402.mp4

**Comment by Caeden117** [comment]
I cannot seem to reproduce this in Stable nor Dev branch. What input device are you trying to use?

**Comment by Yasu3D** [comment]
In that case it was macro buttons on my mouse (Logi G502), but I tried using a standard USB keyboard (HyperX Alloy Core) as well and it just doesn't register more than two inputs.
