### ISSUE TITLE
when i use qosmetic cyoobs it is very glichy/broken

### ISSUE THREAD

**Issue by Junglefresh07** [Caeden117/ChroMapper#424]
**ChroMapper version**
What version of ChroMapper are you running? It can be seen by pressing `Escape` in the Editor, or on the bottom right of the Options menu. If you clone and built ChroMapper from the source, what commit did you clone from?

**Describe the Issue**
Type a clear and concise description of what the problem is.

**Provide Screenshots or Videos**
Providing screenshots and videos (especially if you are encountering an error message) will help a lot to helping us debug the issue.

If the Development Console is open and showing errors, ***PLEASE*** click on the specific error to open the Stack Trace. The "Stack Trace" is the exact location in ChroMapper's code that caused the error, and how it was executed. Providing the Stack Trace with your bug report will allow us to immediately find and fix the problem.

**Steps to Reproduce**
Describe the exact steps which reproduce the problem in as many details as possible.

**Expected Behavior**
What did you expect to happen? How did this differ from what actually happened?

**Additional Context**

**Comment by Caeden117** [comment]
This is completely unrelated to ChroMapper.
