### ISSUE TITLE
Notes in walls

### ISSUE THREAD

**Issue by Xavjer** [Caeden117/ChroMapper#43]
Pixelguy ⭐02/03/2020

notes in front off walls don't look right
https://cdn.discordapp.com/attachments/569722247280066561/673841777505206302/unknown.png
but if you scroll further it does
https://cdn.discordapp.com/attachments/569722247280066561/673841842462261248/unknown.png
same for notes behind walls
https://cdn.discordapp.com/attachments/569722247280066561/673842114219606026/unknown.png

**Comment by Caeden117** [comment]
rendering issues again
