### ISSUE TITLE
ChroMapper softlock when closing Discord

### ISSUE THREAD

**Issue by InterstellarOne** [Caeden117/ChroMapper#441]
**ChroMapper version**
V0.8.0, although this should effect all current versions.

**Describe the Issue**
ChroMapper softlocks when closing Discord while playing a track in "Playing" UI mode. The mouse does not appear, so there is no way to click Ok, and keypresses do not do anything.

**Provide Screenshots or Videos**
![image](https://user-images.githubusercontent.com/63889949/209511515-ede81bf5-4226-4c16-888f-5b966e9b7a99.png)

**Steps to Reproduce**
1. Open Discord on desktop. 
2. Open ChroMapper.
3. Play a map in "Playing" UI mode (Ctrl+H).
4. Press the Windows button, then close Discord.

**Expected Behaviour**
You should be able to close the popup and continue mapping, instead of having to close the app.

**Additional Context**

**Comment by XAce1337manX** [comment]
This soft lock does not happen on either stable or dev as dialogue navigation works. (Press escape or enter). 

v0.8.0 is not a valid version. If it's a v3 build, please specify which commit it's built off. v3 branch is missing a bunch of fixes present in stable/dev.
