### ISSUE TITLE
macOS - ChroMapper requests admin access to Developer Tools, then crashes

### ISSUE THREAD

**Issue by speelbarrow** [Caeden117/ChroMapper#445]
**ChroMapper version**
Built from source ([Universal binary](https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary)) - commit fbf5a83789333346917cc99b2d0d90459eff845e
Downloaded pipeline [build v0.8.523 from Jenkins CI](https://jenkins.kirkstall.top-cat.me/job/ChroMapper/523/) (could not use CML -- see #433)

**System Information**
MacBook Pro, 2020, M1, 13-inch
macOS Ventura 13.1

**Describe the Issue**
Upon launching ChroMapper, when a map is opened the program requests admin permission to access developer tools, hangs for ~30 seconds with a spinning beach ball, then crashes.

**Provide Screenshots or Videos**
https://user-images.githubusercontent.com/44714422/213940557-31268385-dba0-4520-9dbd-88a44509f5bb.mp4
This was the build from source, but the same thing happened with the pipeline build

**Steps to Reproduce**
- Launch ChroMapper
- Open a map

**Additional Context**
- _Occasionally_, it will let me into the editor. However, most of the time it just does this.
- I have a gaming rig running Windows, it has no problem running the app. Haven't tried on Linux but this appears to be a macOS-specific problem
- Other things I've tried (without success):
  - Clicking 'Cancel' when prompted for admin permission -- the app just crashes anyway
  - Opening a map that already exists/using a Beat Saber directory that already exists
  - Building with the "Development Build" option checked

**Comment by BionicBison05** [comment]
Just ran into this myself, can confirm. Running on an M1 Air.

**Comment by XAce1337manX** [comment]
I see an error in the video:
![image](https://github.com/Caeden117/ChroMapper/assets/68104413/fb853f81-83b3-43e6-a02f-7234bece66d4)

Can I get the log from clicking the flagging?

**Comment by BionicBison05** [comment]
@XAce1337manX Here you go:
https://paste.ee/p/kquSv

**Comment by XAce1337manX** [comment]
Fixed with #524
