### ISSUE TITLE
Add the Turkish (Turkey) language

### ISSUE THREAD

**Issue by ramazansancar** [Caeden117/ChroMapper#468]
**What is your request?**
I would like to help with translation to the Turkish(Turkey) language, but it is not added yet. Could it be added?

**What problem does this solve?**
First of all, according to the [official figures](https://data.tuik.gov.tr/Bulten/Index?p=Adrese-Dayali-Nufus-Kayit-Sistemi-Sonuclari-2022-49685) of Turkey's population on February 6, 2023. I would like to share the information that there are 85 million 279 thousand 553 people.
- According to [Steam statistics](https://store.steampowered.com/hwsurvey) data, it ranks 10th among the most used Languages with 1.12%.
According to these statistics, the usage of Turkish is quite high. It can be nice to make the work of Turkish-speaking software developers easier.

**Additional context**

**Comment by Caeden117** [comment]
Sure, Turkish is now an available language on the [CrowdIn page](https://crowdin.com/project/chromapper).

**Comment by ramazansancar** [comment]
> Sure, Turkish is now an available language on the [CrowdIn page](https://crowdin.com/project/chromapper).

Thank you, I will have sent more of them soon
