### ISSUE TITLE
App crash opening editor

### ISSUE THREAD

**Issue by L3Home** [Caeden117/ChroMapper#479]
**ChroMapper version**
v0.8.609

**Describe the Issue**
Entire app hung when entering the editor; no progress or response to input devices.
After closing it, waiting several minutes, then relaunching the app caused it to appear in the "Background processes" in Task Manager (not active Apps) and took about twice the usual time to load. When it finally did, the title bar included the text "(not responding)" for a minute or two before the display finally appeared.

**Provide Screenshots or Videos**
![Screenshot 2023-07-06 152706](https://github.com/Caeden117/ChroMapper/assets/50602111/336d1ed0-749e-406d-ba03-4237aef615cd)
[ChroMapper.exe.17784.zip](https://github.com/Caeden117/ChroMapper/files/11973045/ChroMapper.exe.17784.zip)
[ChroMapper_Issue_Logs.zip](https://github.com/Caeden117/ChroMapper/files/11973088/ChroMapper_Issue_Logs.zip)

**Development Console**
I did attempt to do this, but because the app is truly hung, it is not responding and required me to close the window with the X. I did not have to end the task.
It did produce a CrashDump in Windows; I don't know if you have a way to read them, but I'll attach it too, just in case. I zipped it as the file is 38 MB expanded.
I just now reopened the app and was able to enter the editor for the same song/level as before. It did open (and thank you for fixing the issue with the lines not appearing on new levels!) and that's when I saw the folder icon in the console window. I'm attaching the ones I think may be relevant (ChroMapper, Player, and Player-prev) as I'm not sure which one contains what you need. They do include other errors or warnings so perhaps those will be of interest as well. :)

**Steps to Reproduce**
Editor hangs (with color wheel flickering and progress meter a pac-man that doesn't move) immediately following creating a new Normal level, saving it, opening the editor (with prompt to save the changes I made to the song settings, which I said yes to) and that's where it stopped. Please also note (in case it matters) that I did delete the levels I had created earlier, to start fresh. The song change was just switching to another environment.
It did open (after a much longer time than normal) after I relaunched the app.

**Expected Behavior**
Editor should have opened.

**Additional Context**
n/a

**Comment by Caeden117** [comment]
It appears that you are using plugins that are not compatible for this version of ChroMapper. Some of these have been since integrated into ChroMapper as native features. Please wipe your Plugins folder and try again. If ChroMapper launches, re-download the latest versions of your plugins one at a time, ensuring they still work on the current version.

**Comment by L3Home** [comment]
Will do. I recall that some of the ones I had produced a message about their incompatibility (notably AutoMapper and Selection) so I did remove those when I saw that. I can remove the others; they did work with the v0.8.5xx version I had before updating, but I get that it might have changed. I'm not sure which effects have been added. I would prefer not to need any of these plugins but I don't think all of them have been implemented so I hope I can get those ones back. I'm still really bummed that Selection became incompatible as I really liked that way of selecting objects!

**Comment by L3Home** [comment]
You know, after disabling all of my plugins, not only did the console not show any flags (and thus didn't pop up at all), I also discovered that with all of the updates you've made, I don't see any that I truly think I need. I'm going to run vanilla. :)
