### ISSUE TITLE
Notes buggy after copying notes and walls from standard MM to 360 CM

### ISSUE THREAD

**Issue by Xavjer** [Caeden117/ChroMapper#48]
JohnnyDee 01/31/2020
created a diff for 360 in cm -> copied the notes and walls in mm from a standard difficulty into that difficulty -> https://youtu.be/4UO-jl61jig
YouTube
Johnny Dee
Chromapper 360 bug

Caeden117 01/31/2020
Click refresh rotations
Does that fix
JohnnyDee 02/01/2020
i forgot to record but no did not
after reloading i can see the notes far in the distance but they are not moving towards me
you can see that in the vid too
but they show up in the topleft "last bloq thingy" correctly

**Comment by Caeden117** [comment]
possibly fixed, reopen the issue if this persists
