### ISSUE TITLE
Unable to switch to Dev channel on Fedora

### ISSUE THREAD

**Issue by SoapyMan** [Caeden117/ChroMapper#481]
**ChroMapper version**
Running latest launcher (CML_Linux) from web site in the repo description

**Describe the Issue**
I've changed update channel to Dev in Experimental settings. Relaunching does nothing apart from launching Chromapper itself, but in the top right corner now appears a message "Update Available". Clicking at it closes ChroMapper and nothing occurs further.

**Steps to Reproduce**
1. Have Fedora Linux 38
2. `sudo dnf install mono-develop`
3. run `mono ./CML_Linux`
4. Change to Dev channel in Experimental settings
5. Close Chromapper and run `mono ./CML_Linux` again
6. See that launcher just launches Chromapper without updating it

**Expected Behavior**
Chromapper getting updated

**Comment by XAce1337manX** [comment]
Closing as stale. Reopen if issue persists.
Latest version of CML also no longer requires mono.
