### ISSUE TITLE
Chromapper keeps getting deleted on startup?

### ISSUE THREAD

**Issue by Ethan-Joven** [Caeden117/ChroMapper#482]
**ChroMapper version**
Running Version 0.8.523 (latest version) for Windows

**Describe the Issue**
Everytime I install Chromapper, the next time I boot up my PC to go into chromapper again, I click the shortcut on my taskbar and it says that the .exe file for chromapper was deleted, asking me if I want to delete the shortcut. I look in the chromapper files to see that the .exe itself is missing?

**Provide Screenshots or Videos**
![Screenshot](https://github.com/Caeden117/ChroMapper/assets/87787738/acfec702-a687-4dfd-9047-2c71badacc0a)

**Steps to Reproduce**
Download CML from the website, run it, wait for it to open chromapper, close chromapper, restart pc, and try to open chromapper.

**Expected Behavior**
I expected it to delete the .exe like usual, and it did.

**Additional Context**
This may be an issue on only my PC as I didn't see any other issues, open or closed, regarding this.

**Comment by Ethan-Joven** [comment]
I forgot to mention, the screenshot isn't excactly correct but the .exe file getting deleted keeps making me download the launcher again, just for it to get deleted the next time I boot up my PC.

**Comment by Caeden117** [comment]
Your anti-virus might be messing with the ChroMapper installation. Move the ChroMapper launcher out of the `Downloads` folder (preferably a secondary drive or your Desktop) then try launching again.

**Comment by Ethan-Joven** [comment]
> Your anti-virus might be messing with the ChroMapper installation. Move the ChroMapper launcher out of the `Downloads` folder (preferably a secondary drive or your Desktop) then try launching again.

I'll try it and update you the next time I start up my PC

**Comment by Ethan-Joven** [comment]
Update: your suggestion helped. Tysm @Caeden117
