### ISSUE TITLE
Text Disappearing on macOS

### ISSUE THREAD

**Issue by abduelhamit** [Caeden117/ChroMapper#483]
**ChroMapper version**
Both stable (v0.8.523) and dev (v0.8.628) channels.

**Describe the Issue**
When I open the editor, the text on the buttons and some other places disappears. Some other labels, like the tooltips, are not affected.

**Provide Screenshots or Videos**
These are from the dev (v0.8.628) channel.

Before going into the editor:
<img width="1157" alt="Bildschirmfoto 2023-09-03 um 08 29 17" src="https://github.com/Caeden117/ChroMapper/assets/4894360/99764f45-03d8-43b8-aaca-ccf62c55a8ed">
<img width="1157" alt="Bildschirmfoto 2023-09-03 um 08 29 30" src="https://github.com/Caeden117/ChroMapper/assets/4894360/0b4fe63a-8245-4cf1-9b21-c1a731af9739">

After the bug happens:
<img width="1157" alt="Bildschirmfoto 2023-09-03 um 08 29 55" src="https://github.com/Caeden117/ChroMapper/assets/4894360/637585d7-d538-454b-8544-3fd9952e862d">
<img width="1157" alt="Bildschirmfoto 2023-09-03 um 08 30 07" src="https://github.com/Caeden117/ChroMapper/assets/4894360/5aeea653-4b76-4ae6-b54c-6d196bc7b727">
<img width="1157" alt="Bildschirmfoto 2023-09-03 um 08 30 15" src="https://github.com/Caeden117/ChroMapper/assets/4894360/0b0edf4c-9d7e-489f-a2a3-f57c055a10ea">
<img width="1157" alt="Bildschirmfoto 2023-09-03 um 08 30 21" src="https://github.com/Caeden117/ChroMapper/assets/4894360/6491b8c7-f335-4822-abf6-78c42e123056">

**Steps to Reproduce**
Just open any song in the editor.

**Expected Behavior**
I expect that the text will stay.

**Additional Context**
Hardware: MacBook Air, 15", M2, 2023
System: macOS Ventura 13.4.1

**Comment by XAce1337manX** [comment]
Looks like the fix above works for some: v0.8.631

**Comment by abduelhamit** [comment]
Yep, that fixed it for me. Thanks. 👍
