### ISSUE TITLE
BPM doesn't change in the editor even when changed in the Song Info Screen

### ISSUE THREAD

**Issue by Koreami** [Caeden117/ChroMapper#486]
**ChroMapper version**
Development Build v0.8.643

**Describe the Issue**
BPM does not change in the actual editor. (The default is 100 BPM, yet when I change it in the song info screen, it doesn't change in the editor.)

**Provide Screenshots or Videos**
How it looks like without opening the editor after setting everything up.
![image](https://github.com/Caeden117/ChroMapper/assets/67789905/7ddabbbc-03a0-4dac-855d-6b874797dd8b)

Reproducing this error with a new song:
Song info screen:
![image](https://github.com/Caeden117/ChroMapper/assets/67789905/aa4c5d92-05a8-43c6-bb85-795511dfa417)

Opening the editor (BPM says 100 instead of 200):
![image](https://github.com/Caeden117/ChroMapper/assets/67789905/1c238b82-d648-4da2-b2c0-f75d39a247b6)

If the Development Console is open and showing errors, ***PLEASE*** click on the specific error to open the Stack Trace. The "Stack Trace" is the exact location in ChroMapper's code that caused the error, and how it was executed. Providing the Stack Trace with your bug report will allow us to immediately find and fix the problem.

^Not applicable, no errors in console (white and purple stuff).

**Steps to Reproduce**
1. Create new map, add audio, etc.,
2. Set the BPM in the song info screen.
3. Open the editor

**Expected Behavior**
I expected that the BPM in the editor would be the same BPM as the one I inputted into the song info screen.

**Additional Context**
Downloaded from GitHub, am on Windows 10, if that matters.
I mean you can change the BPM in the editor again manually but that is a teensy weensy bit annoying.

**Comment by Koreami** [comment]
goji: "this is actually not a bug, instead it's due to how official editor BPM changes work. You'll have to delete that bpm change at beat 0 for it to update your set bpm, very annoying but it's just how it is"

**Comment by XAce1337manX** [comment]
While not a bug, the workflow sucks so it will be changed.
