### ISSUE TITLE
Can't open V3 map after switching to dev branch and back

### ISSUE THREAD

**Issue by LostALife** [Caeden117/ChroMapper#490]
**ChroMapper version**
v0.9.646

**Describe the Issue**
I updated Chromapper, the console started popping up when I started the software, but I didn't pay much attention to it.
I started work on a new map with V3 notes and was working fine. I decided to switch to dev and back to stable since that was what originally caused the console to show up. The console continued to show, but now when I open the new map I was working on I get an error stating V3ColorNote missing required node "y". The bug report generated is below.

https://paste.ee/p/KysUi

If I try to then open the editor for the map, I get a message stating "The selected difficulty doesn't exist! Have you saved after creating it?". More text is added to the console, the bug report for that is below.

https://paste.ee/p/6rhTD

If the Development Console is open and showing errors, ***PLEASE*** click on the specific error to open the Stack Trace. The "Stack Trace" is the exact location in ChroMapper's code that caused the error, and how it was executed. Providing the Stack Trace with your bug report will allow us to immediately find and fix the problem.

Clicking the error doesn't appear to do anything, so I have just added bug reports.

**Steps to Reproduce**
- Switch to dev
- Update and restart
- Switch to stable
- Update and restart
- Create new V3 map and add notes
- Switch to dev
- Update and restart
- Switch to stable
- Update and restart
- Try to reopen map

**Comment by XAce1337manX** [comment]
If you edit a map in Dev CM and you need to bring it to stable, do the following:
1. Disable the Save Without Default Values setting (in general settings).
2. Resave all difficulties that have been saved in Dev.
3. Switch release channel to Stable and relaunch CM.
4. Resave all difficulties in Stable.
5. Remove `"vfxEventBoxGroups": []` and `"_fxEventCollection": {}` by json editing.

This will be fixed soon once #489 is merged.

**Comment by LostALife** [comment]
Thanks, that worked!
