### ISSUE TITLE
Can't click on anything within ChroMapper

### ISSUE THREAD

**Issue by ericswpark** [Caeden117/ChroMapper#497]
**ChroMapper version**
What version of ChroMapper are you running? It can be seen by pressing `Escape` in the Editor, or on the bottom right of the Options menu. If you clone and built ChroMapper from the source, what commit did you clone from?
Development Build

**Describe the Issue**
Type a clear and concise description of what the problem is.

I can't click on any of the dialogs or buttons within ChroMapper.

At one point I managed to get past the "Discord RPC has encountered an error" dialog by using the tab and enter keys, but that didn't work for the "First Time Setup" dialog right behind it. I couldn't capture it in the repro video below (it didn't work).

**Provide Screenshots or Videos**
Providing screenshots and videos (especially if you are encountering an error message) will help a lot to helping us debug the issue.

https://github.com/Caeden117/ChroMapper/assets/13326074/3ef233e6-f1d2-4f1c-9ce9-d28e116ca468

If the Development Console is open and showing errors, ***PLEASE*** click on the specific error to open the Stack Trace. The "Stack Trace" is the exact location in ChroMapper's code that caused the error, and how it was executed. Providing the Stack Trace with your bug report will allow us to immediately find and fix the problem.

**Steps to Reproduce**
Describe the exact steps which reproduce the problem in as many details as possible.
1. Launch ChroMapper
2. Observe bug

**Expected Behavior**
What did you expect to happen? How did this differ from what actually happened?
Items should be clickable within ChroMapper

**Additional Context**
I'm running macOS Sonoma 14.2.1 (23C71).

**Comment by paxblueribbon** [comment]
Seeing this same issue, only since updating to the latest mac version, 14.2.1

**Comment by paytontech** [comment]
Having the same issue, latest version, macOS 14.3.1, CML 1.13

**Comment by FireEntity1** [comment]
Same issue on macOS 14.2.1. ChroMapper is unusable on Sonoma.

**Comment by Caeden117** [comment]
We've been making fixes to ChroMapper on Apple Silicon as we go. You can [try manually switching to the Development channel](https://chromapper.atlassian.net/wiki/spaces/UG/pages/806682666/Frequently+Asked+Questions+FAQ#Why-am-I-stuck-on-the-first-screen-on-M1-mac%3F) and downloading our latest fixes.

Unfortunately, none of the ChroMapper developers have an Apple Silicon device to thoroughly debug and solve issues with. We're primarily Windows developers hoping that Unity is stable enough to Just Work™️ on Apple Silicon.

**Comment by XAce1337manX** [comment]
Fixed with #524
