### ISSUE TITLE
Chromapper can't update, launcher not working either

### ISSUE THREAD

**Issue by Vasecarpet124** [Caeden117/ChroMapper#505]
**ChroMapper version**
v0.8.497 is the version im using, that works, but this is irellevant, as I am unable to update.

**Describe the Issue**
I would like to update, however the launcher downloaded from the website doesn't work nor does clicking the "Update available" button in chromapper.
Chromapper launcher not working, nothing happens when opened. Attempted to launch with admin, redownloaded multiple times, moved EXE location, restarted pc, uninstalled current version of chromapper (deleting the folder), nothing works.

**Provide Screenshots or Videos**
![image](https://github.com/Caeden117/ChroMapper/assets/50207878/07683045-c0f9-48a7-93fa-9d6a3f9a877d)
This is an image of the installation folder (F:/cml) and the CML.exe when launched does not open.
![image](https://github.com/Caeden117/ChroMapper/assets/50207878/3cc5e8c8-f717-4f74-a370-e7b4123b3996)
Similar to the last one, the launcher downloaded from the ChroMapper Downloads website (https://cm.topc.at/dl) which also does not open.
![image](https://github.com/Caeden117/ChroMapper/assets/50207878/7d698421-878d-41b6-bb9f-270354d65ec6)
This is an image of the chromapper folder in my installation directory. This ChroMapper.exe does work, as it is already installed, but when attempting to update using the "Update available" button...
![image](https://github.com/Caeden117/ChroMapper/assets/50207878/285f3954-28c5-4753-8b23-02356995a985)
... it does not work. The app closes automatically and does not open, and when re-opening the app, it shows the same, as if I hadn't clicked the button. Essentially the app crashes when clicking the button.

**Steps to Reproduce**
Download the latest chromapper version and run the launcher. For me, it does not open.
You could try to install the version of chromapper that was out as of 22 december 2022, as that is the current chromapper version i am using, and then try to run the CML.exe.

**Expected Behavior**
I expected the launcher to open and install the latest version of chromapper. This is not the case. It does not open.

**Additional Context**
As previously mentioned, the launcher does not work, both the latest and the currently downloaded one (downloaded 22 december 2022). Due to this, I am unable to update and am stuck on v0.8.497 and I'm also unable to switch to developer branch.
I have attempted to build chromapper from both branches, and it has failed. Most likely my fault, as it was telling me to install some Git thing, but nothing changed when I installed it. I have read as many bug reports and reddit posts as I could bare, and yet no one had a solution.

**Comment by XAce1337manX** [comment]
Closing as stale. Reopen if issue persists.
