### ISSUE TITLE
Cannot find united mapping host session button

### ISSUE THREAD

**Issue by FredsMedia** [Caeden117/ChroMapper#514]
**ChroMapper version**
v0.9.690

**Describe the Issue**
I cannot find anywhere on how to host a chromapper united mapping session both in the app and online. 

**Provide Screenshots or Videos**
N/A

If the Development Console is open and showing errors, ***PLEASE*** click on the specific error to open the Stack Trace. The "Stack Trace" is the exact location in ChroMapper's code that caused the error, and how it was executed. Providing the Stack Trace with your bug report will allow us to immediately find and fix the problem.

**Steps to Reproduce**
Open chromapper, open a map, open the editor, nothing both in the editor screen or the pause menu.

**Expected Behavior**
I expected there to be a button to launch a C.U.M session.

**Additional Context**
I am on windows and using the chromapper launcher.

**Comment by XAce1337manX** [comment]
Press tab in the editor. 
![image](https://github.com/Caeden117/ChroMapper/assets/68104413/361ac6b6-c001-4006-9df4-ebb75dd1e742)

**Comment by FredsMedia** [comment]
I tried to host over direct connection with the person on the same network, but it timed out. I assume I wouldn't need to port forward if it's going through LAN.
