### ISSUE TITLE
Keep Crashing on Mac

### ISSUE THREAD

**Issue by Jaydenha09** [Caeden117/ChroMapper#519]
**ChroMapper version**
ChroMapper 0.9.690

**Describe the Issue**
Try to edit a project, and it is loading for something, after it crashed, seems like its trying to load discord rpc but failed
**Provide Screenshots or Videos**

If the Development Console is open and showing errors, ***PLEASE*** click on the specific error to open the Stack Trace. The "Stack Trace" is the exact location in ChroMapper's code that caused the error, and how it was executed. Providing the Stack Trace with your bug report will allow us to immediately find and fix the problem.

**Steps to Reproduce**
Describe the exact steps which reproduce the problem in as many details as possible.

**Expected Behavior**
What did you expect to happen? How did this differ from what actually happened?

**Additional Context**

**Comment by Jaydenha09** [comment]
![Video](https://fm.jaydenha.uk/api/public/dl/hDinoSZK/main_storage/Screen%20Recording%202024-03-26%20at%2012.45.13%E2%80%AFAM.mov)

**Comment by Jaydenha09** [comment]
[Video](https://fm.jaydenha.uk/api/public/dl/hDinoSZK?inline=true)

**Comment by Caeden117** [comment]
We're currently working to restore Apple Silicon compatibility. Have some patience; none of us have Apple Silicon devices to personally debug with.

**Comment by Jaydenha09** [comment]
Will it work on aarch64 Fedora? I installed asahi linux on it

**Comment by Jaydenha09** [comment]
but sometimes it works, I have no idea why
<img width="1191" alt="image" src="https://github.com/Caeden117/ChroMapper/assets/98650905/f2f9a8af-928d-4159-8944-c7a863d1e453">

**Comment by Caeden117** [comment]
Our Linux distributable currently targets x64. The only ARM distribution we provide via the ChroMapper Launcher is the unified x64/ARM macOS distributable. If you want to run ChroMapper on Asahi Linux, it'll be up to you to follow our build guide and build for Linux ARM. 

Alternatively, you can try [manually switching to our development release channel](https://chromapper.atlassian.net/wiki/spaces/UG/pages/806682666/Frequently+Asked+Questions+FAQ#Why-does-ChroMapper-crash-on-start-up-on-M1-mac?) to receive our latest fixes for Apple Silicon.

**Comment by Jaydenha09** [comment]
yea its working fine after I disabled discord rpc, maybe someone can try to build a version that removed discord rpc, it will work

**Comment by Jaydenha09** [comment]
> Our Linux distributable currently targets x64. The only ARM distribution we provide via the ChroMapper Launcher is the unified x64/ARM macOS distributable. If you want to run ChroMapper on Asahi Linux, it'll be up to you to follow our build guide and build for Linux ARM.
> 
> Alternatively, you can try [manually switching to our development release channel](https://chromapper.atlassian.net/wiki/spaces/UG/pages/806682666/Frequently+Asked+Questions+FAQ#Why-does-ChroMapper-crash-on-start-up-on-M1-mac?) to receive our latest fixes for Apple Silicon.

ok thanks for telling me that, I will try building it

**Comment by Jaydenha09** [comment]
Now there is another problem, it wont be downloaded if I deleted it, now its not downloading and I can not do anything, can't you just release complied binary and list all versions in the website instead making a installer with bug? thanks

**Comment by Top-Cat** [comment]
And have you never update thus making supporting 1000s of versions hell? No.
If you have a problem with the launcher feel free to fix it, it's open source.

As a workaround maybe try deleting `~/Library/Preferences/at.topc.cm.launcher.plist`

**Comment by XAce1337manX** [comment]
Should be fixed by (#524)
