### ISSUE TITLE
macOS - Unable to interact with anything inside Chromapper

### ISSUE THREAD

**Issue by FireEntity1** [Caeden117/ChroMapper#521]
**ChroMapper version**
Latest download

**Describe the Issue**
Upon launcher Chromapper and entering the setup screen, I am unable to interact with anything. This includes changing settings, continuing, or entering the editor. I cannot get past setup.

**Provide Screenshots or Videos**
https://github.com/Caeden117/ChroMapper/assets/134467282/812b60b1-a686-4233-8a5e-a212fe3df32b

**Steps to Reproduce**
Download Chromapper, launch app on macOS.

**Expected Behavior**
Ability to interact with and use the software.

**Additional Context**
Running macOS Sonoma, Intel MacBook Pro

**Comment by XAce1337manX** [comment]
This issue is fixed in dev release channel. Until it is merged into stable, to opt into this channel see:
https://chromapper.atlassian.net/wiki/spaces/UG/pages/806682666/Frequently+Asked+Questions+FAQ#Why-am-I-stuck-on-the-first-screen-on-M1-mac?

**Comment by FireEntity1** [comment]
> Look for a file ChroMapperSettings.json in ~/Library/Application Support/com.BinaryElement.ChroMapper, change the value for ReleaseChannel, and restart ChroMapper to update to dev release:

com.BinaryElement.ChroMapper does not exist in Application Support. I have looked through the app package files and I cannot find anything similar that contains a dev channel option.
