### ISSUE TITLE
ChroMapper won't launch from my MacBook.

### ISSUE THREAD

**Issue by Fierce7114** [Caeden117/ChroMapper#528]
**ChroMapper version**
What version of ChroMapper are you running? It can be seen by pressing `Escape` in the Editor, or on the bottom right of the Options menu. If you clone and built ChroMapper from the source, what commit did you clone from?

v0.9.690

**Describe the Issue**
Type a clear and concise description of what the problem is.

Whenever I try to open ChroMapper from my app finder on my MacBook, it doesn't show up in my app bar at the bottom. It does the same when I ctrl + click > open. Whenever I try to open it from CML, it always pulls up the update checker for a split second. Then it goes away and doesn't let me open ChroMapper. 

**Provide Screenshots or Videos**
Providing screenshots and videos (especially if you are encountering an error message) will help a lot to helping us debug the issue.

https://github.com/Caeden117/ChroMapper/assets/172834880/32957848-f353-445b-bdb9-3219fb1bcb88

If the Development Console is open and showing errors, ***PLEASE*** click on the specific error to open the Stack Trace. The "Stack Trace" is the exact location in ChroMapper's code that caused the error, and how it was executed. Providing the Stack

https://github.com/Caeden117/ChroMapper/assets/172834880/6f84de3b-a7d2-463c-aee9-5eea3f6c5674

https://github.com/Caeden117/ChroMapper/assets/172834880/ec40f8d9-f28f-4ea0-9cc8-22892bf9d1f1

 Trace with your bug report will allow us to immediately find and fix the problem.

**Steps to Reproduce**
Describe the exact steps which reproduce the problem in as many details as possible.

1. Go to finder
2. Click CML/ChroMapper
3. Notice that it doesn't work

**Expected Behavior**
What did you expect to happen? How did this differ from what actually happened?

I expected ChroMapper/CML to open as normal. It didn't open at all.

**Additional Context**

Also, I did switch to dev ChroMapper the other day. I have installed no Plug-Ins. I know there's a new version of ChroMapper (v0.10.697) but it won't let open ChroMapper at all. Thanks for any help.

**Comment by Caeden117** [comment]
We've just got access to an Apple Silicon device recently, so we're trying to debug and resolve many of the macOS / Apple Silicon problems preventing ChroMapper from launching or otherwise working as intended. We should hopefully get ChroMapper on Apple Silicon in a much better position soon.

**Comment by Fierce7114** [comment]
On Saturday, June 15, 2024, Caeden117 ***@***.***> wrote:
> We've just got access to an Apple Silicon device recently, so we're
trying to debug and resolve many of the macOS / Apple Silicon problems
preventing ChroMapper from launching or otherwise working as intended. We
should hopefully get ChroMapper on Apple Silicon in a much better position
soon.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci3.googleusercontent.com/meips/ADKq_NYNGHR6BiohT_rcjMJ6MfeAJHBipRQeBm52KCFL4j6BdxmAlJdBfBK8Y8aeDrkrsSKKLxHdRd5dusYoBji20OXs_Huq5tMyvPljLZT0yLeEQhuC9PTFHSgm7omgo4Lxn_M7Xz8B78wIGr0yM58FKcyiZ4Ic9amQTxZxU6VceD_ubDfOcaGeRNF7RUTtRTofi1zkpW-LjuSQvVSGrmvygFLy-xSKJWqLHJ-RE8tyaodXIOJZIcOky94=s0-d-e1-ft#https://github.com/notifications/beacon/BJGUAQDA3A45LBYEWRS4JBDZHSKXZA5CNFSM6AAAAABJKUJ5WCWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTUBMC6LS.gif>Message
ID: ***@***.***>

Great! Appreciate it. Ty and have a great day :)

-- 
Fierce7114

**Comment by XAce1337manX** [comment]
Resolved since previous stable release.
