### ISSUE TITLE
ChroMapper ships with folder having 

### ISSUE THREAD

**Issue by egginabox0** [Caeden117/ChroMapper#532]
**Version**: 0.10.763

**Description**
ChroMapper ships with a folder labeled with a `DoNotShip` suffix
**Media**
![image](https://github.com/Caeden117/ChroMapper/assets/98293106/52102786-c550-4caf-a237-aa56d86b2706)

**Steps to Reproduce**
Download version 0.10.763

**Expected Behavior**
Developers/Contributors may not have wanted to ship this `ChroMapper_BurstDebugInformation_DoNotShip` folder.

**Additional Context**
Upgraded from a previous unknown version.

**Comment by Caeden117** [comment]
This is a Unity compiled folder. It's just stuff related to the Burst compiler which could reveal parts of the source code.... which doesn't really matter when ChroMapper is open source.
