### ISSUE TITLE
Beatmaps don't load

### ISSUE THREAD

**Issue by MrCubicYT** [Caeden117/ChroMapper#533]
**ChroMapper version**
Dev V0.10.769 and Stable.

**Describe the Issue**
Beatmaps don't load, Chromapper gets stuck on infinite loading screen.

**Provide Screenshots or Videos**
![image](https://github.com/Caeden117/ChroMapper/assets/132150361/e70ee0cd-2363-44c7-a953-19bc1ffb1aa1)

**Steps to Reproduce**
Load a map, seems like a me problem tho...

**Expected Behavior**
The map loads so I can edit the difficulty (I can still edit song details).

**Additional Context**
Nah.

**Comment by XAce1337manX** [comment]
The errors there are caused by outdated plugins. Remove them and try again.

**Comment by MrCubicYT** [comment]
this worked 😄👍
