### ISSUE TITLE
ChroMapper doesn't start

### ISSUE THREAD

**Issue by david-marco** [Caeden117/ChroMapper#538]
**ChroMapper version**
I don't know, and I can't find out because it doesn't launch

**Describe the Issue**
ChroMapper just doesn't launch on linux

**Provide Screenshots or Videos**
No error messages, just no respond.

**Steps to Reproduce**
Launch the linux executable

**Expected Behavior**
I expected it to open something? But obviously nothing works.

**Additional Context**
I just see it appear in the background in the process monitor. (here is the screenshot)
![image](https://github.com/user-attachments/assets/d0bf1d8c-af2b-4af1-93c6-038bb106995b)

**Comment by MoistSac** [comment]
CNL-Linux doesn't have any GUI progress indicator, it just downloads/updates in the background and launches it when ready. To see a progress indicator, launch it from the terminal, eg `cd` to its location and run `./CML-Linux`
