### ISSUE TITLE
I can't run ChroMapper.

### ISSUE THREAD

**Issue by ItzKony** [Caeden117/ChroMapper#555]
**ChroMapper version**
The latest one

**Describe the Issue**
Well.. I just can't open CML. 

**Steps to Reproduce**
- I downloaded CML and launched it.

![image_2024-12-18_181950500](https://github.com/user-attachments/assets/631d68c2-94f9-4055-98d4-8cffbae18e38)

**Comment by XAce1337manX** [comment]
As error message states. Do not run as admin.
In this case, it was caused by disabled UAC settings on never notify.

**Comment by ncflagg** [comment]
Why is this the case? I am not running the app as admin; but I AM in the administrators group. I also have UAC disabled. Why this arbitrary requirement? I can run the app as another user on my Windows system, but why should I have to do that?

`runas /user:<user here> CML.exe`

**Comment by Caeden117** [comment]
When running as Admin, the active directory for the process changes to `C:\Windows\System32`. While this is fine for most of ChroMapper, this affects plugin loading as it tries to load plugins from `C:\Windows\System32\Plugins` which throws a `System.IO.UnauthorizedAccessException` error.

Another common fix is to remove CML from common Windows protected directories such as the Downloads folder. In my personal case, I have ChroMapper installed on my secondary data drive, and that works fine.

**Comment by ncflagg** [comment]
Interesting. Your workaround does not work in my case. I'm running it from C:\Portable\\..
