### ISSUE TITLE
Credits Screen visual glitches

### ISSUE THREAD

**Issue by Xavjer** [Caeden117/ChroMapper#58]
Screen is not starting at the Top (Probably under the ChroMapper Display

Huge gap between Closed Alpha Testers title and the actual testers.

Patreon Supporters is overlaying the alpha testers

Is the data correct?, I don't see myself for example :)

**Comment by Caeden117** [comment]
I haven't looked into any Patreon API for ChroMapper, so I have to update the list manually.

I'll plan on fixing this when the new options menu is pulled (See #49)

**Comment by Xavjer** [comment]
That's a very low prio one, agreed. I would Label it but I don't have the necessary rights to do so ;)
