### ISSUE TITLE
Raycast Blocker not working in Node Editor

### ISSUE THREAD

**Issue by Xavjer** [Caeden117/ChroMapper#61]
Swifter 2020-02-18 at 1:21 AM
this happens a lot
https://cdn.discordapp.com/attachments/569722247280066561/679120156730982440/Desktop_2020.02.17_-_15.04.03.72.DVR_1.mp4

the issue here is that you can delete things that are BEHIND the node editor window
and than I think it doesn't add it to the list of things you can undo, because it was only looking at the editor?

**Comment by Caeden117** [comment]
Raycast issues such as this should be mostly fixed now.
