### ISSUE TITLE
[FEATURE] Precision Placement Grid

### ISSUE THREAD

**Issue by Xavjer** [Caeden117/ChroMapper#62]
Swifter 2020-02-19 at 2:31 AM
is precision placement planned for chromapper?

RyanTheTechMan 2020-02-19 at 2:33 AM
you already can by using the Node Editor.
there currently is no grid for it though.

**Comment by Caeden117** [comment]
Added in commit d4da73fa71a3b469f69cb74dbb89182669cb6177
