### ISSUE TITLE
NullReferenceException dragging nodes under some circumstances

### ISSUE THREAD

**Issue by Xavjer** [Caeden117/ChroMapper#65]
Open Map with existing Event Nodes
Alt+ Drag a node around, then delete it with Ctrl+Shift+MiddleMouse

Go to Ring Propagation (Press P)

=>

NullReferenceException: Object reference not set to an instance of an object
SimpleJSON.JSONLazyCreator.Set (SimpleJSON.JSONNode aVal) (at Assets/Plugins/SimpleJSON.cs:1044)
SimpleJSON.JSONLazyCreator.set_Item (System.String aKey, SimpleJSON.JSONNode value) (at Assets/Plugins/SimpleJSON.cs:1067)
EventPlacement.OnPhysicsRaycast (UnityEngine.RaycastHit hit, UnityEngine.Vector3 transformedPoint) (at Assets/__Scripts/MapEditor/Mapping/PlacementControllers/EventPlacement.cs:57)
PlacementController`3[BO,BOC,BOCC].Update () (at Assets/__Scripts/MapEditor/Mapping/PlacementControllers/PlacementController.cs:130)

**Comment by Caeden117** [comment]
Should be fixed in the `dev` branch, re-open the issue if it persists
