### ISSUE TITLE
Non ring propagation events selected when switching into propagation => Strange appearance

### ISSUE THREAD

**Issue by Xavjer** [Caeden117/ChroMapper#66]
Currently, if I select event that are not Big Rings and switch mode (P), I will get some blueish nodes off the grid being displayed.

I am unsure how we should solve this issue, we could:

1. Deselect all events that are not big rings
2. Notify the user that this is not possible while having non big rings selected
3. Deselect all

Probably other possibilities

**Comment by Caeden117** [comment]
The blueish notes you're seeing is actually the selection material persisting (I think I just change the alpha of the events to 0, so they're still "loaded", just invisible)

I think the easiest and safest way to go about this is to go with option 1.
