### ISSUE TITLE
[FEATURE] Support for 3D (space) mouse within ChroMapper

### ISSUE THREAD

**Issue by Xavjer** [Caeden117/ChroMapper#67]
As I personally own a 3dconnexion mouse, I think that this may be a great addition to ChroMapper and would allow it for maps to be created even faster.

Map the buttons for example like:
1Button to switch between FreeFlight (Like right clicking) and Follow (If you fly forward, the grid will move with you into the song) mode

Other buttons used for the most used operations.

Just wondering if I am the only one out there having such a mouse. If desired, I would gather the SDK from 3D Connexion and implement the support for it.

**Comment by Caeden117** [comment]
I do not mind if you implement the support for your mouse, however given the state of CM's input as is, I think it might be better if we hold off until the new [Input System](https://github.com/Caeden117/ChroMapper/tree/unity-2019.3#unity-20193-branch) is implemented.

**Comment by Caeden117** [comment]
Closing due to age, if you would like to implement 3D Mouse support then do consider making a pull request (I don't own one myself)
