### ISSUE TITLE
Long Walls "disappear" if the beginning is out of the loaded zone

### ISSUE THREAD

**Issue by Xavjer** [Caeden117/ChroMapper#73]
Swifter 2020-02-23 at 11:14 PM
ok so I have some really long walls in my map
when I scroll too far the walls kinda disappear
is is possible to keep walls loaded if the rest of them is still in a loaded chunk?

**Comment by Caeden117** [comment]
Fixed in commit 757de816119227b0a7643cea4c9ed04f98e5b2e8 on the `dev` branch
