### ISSUE TITLE
Undo moved notes will not show correctly in the current row

### ISSUE THREAD

**Issue by Xavjer** [Caeden117/ChroMapper#75]
shad 2020-02-24 at 4:48 AM
Notes look like they're behind the grid now
https://cdn.discordapp.com/attachments/569722247280066561/681346621417455636/unknown.png

When trying to undo a note moved by alt + leftclick

**Comment by Caeden117** [comment]
Fixed in commit a400954968cb681a0c7dca2536d7dd651ca98700
