### ISSUE TITLE
when mapping 360 and toggling rotate track multiple times goiong to beginning will not reset the rotation

### ISSUE THREAD

**Issue by Futuremappermydud** [Caeden117/ChroMapper#86]
![image](https://user-images.githubusercontent.com/54294576/76136929-11535b80-6005-11ea-8834-a440b0b8c225.png)
no events were put before

**Comment by Caeden117** [comment]
This has been fixed in the [`dev`](https://github.com/Caeden117/ChroMapper/tree/dev) branch for a little while
